[package]
name = "starpc-build"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Code generation for starpc"
keywords.workspace = true
categories.workspace = true

[dependencies]
prost-build = { workspace = true }
